### PR TITLE
apple x86_64 (intel, not apple m1 silicon) support

### PR DESCRIPTION
**Pull request by brandonros**

### CODE REVIEW

**Comment by bri3d** [comment]
I use this on my M1 MBA already - gcc is just an alias to `clang` with the Apple toolchain. Using clang directly is definitely more correct though

**Comment by brandonros** [comment]
@bri3d i think you know this but there's a "subtle difference" between building for `arm64` and `x64`. not saying this PR fixes that, curious to hear what kind of result you had.

```
$ file *
op20pt32.dll:                        PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
op20pt64.dll:                        PE32+ executable (DLL) (GUI) x86-64, for MS Windows
tactrix-openport-darwin-arm64.dylib: Mach-O 64-bit dynamically linked shared library arm64
tactrix-openport-darwin-x64.dylib:   Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by bri3d** [comment]
not sure I follow. I've been using the `j2534.dylib: Mach-O 64-bit dynamically linked shared library arm64` produced by `gcc -g -shared j2534.o `pkg-config --cflags --libs libusb-1.0` -o j2534.dylib` to reflash successfully on my M1 MacBook Air (with this consuming driver: https://github.com/bri3d/VW_Flash/blob/osx-j2534/lib/j2534.py ) for a long time now - so I really didn't do any work or investigation into any differences because it Just Worked. Actually this hasn't been tested on x86_64 so maybe that's where the differences come in 😂

**Comment by brandonros** [comment]
g

**Pull request closed without merging**
